export const darkTheme = {
  colors: {
    'base-white': '#FFFFFF',
    'base-background': '#151718',
    'base-card': '#1F2223',
    'base-input': '#222526',
    'base-button': '#262A2B',
    'base-hover': '#272A3C',
    'base-label': '#8D8686',
    'base-text': '#D1CDC7',
    'base-subtitle': '#D1CDC7',
    'base-title': '#D1CDC7',
    'base-error': '#f84747',
    'brand-purple-dark': '#844DF8',
    'brand-purple': '#8047F8',
    'brand-purple-light': '#212425',
    'brand-yellow-dark': '#EAA948',
    'brand-yellow': '#DBAC2C',
    'brand-yellow-light': '#372F0E',
  },
  textSizes: {
    'title-title-xl': '3rem',
    'title-title-l': '2rem',
    'title-title-m': '1.5rem',
    'title-title-s': '1.2rem',
    'title-title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-bold-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-button-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}
